"""
Example: using ff-kit locally — NO API keys, NO LLM needed.

This script demonstrates every core operation using a test video
generated by FFmpeg itself. Just run it:

    python examples/local_example.py

Prerequisites:
    pip install ff-kit
    ffmpeg must be on your PATH
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path

from ff_kit import clip, merge, extract_audio, transcode
from ff_kit.executor import Executor


def main() -> None:
    work = Path(tempfile.mkdtemp(prefix="ffkit_demo_"))
    print(f"Working directory: {work}\n")

    # ── 0. Generate a 10-second test video with FFmpeg ────────────
    print("0. Generating a 10s test video...")
    exe = Executor()
    test_video = str(work / "test_input.mp4")
    exe.run([
        "-f", "lavfi", "-i",
        "testsrc=duration=10:size=640x360:rate=25",
        "-f", "lavfi", "-i",
        "sine=frequency=440:duration=10",
        "-c:v", "libx264", "-preset", "ultrafast",
        "-c:a", "aac", "-shortest",
        test_video,
    ], output_path=test_video)
    print(f"   Created: {test_video}\n")

    # ── 1. Clip: extract seconds 2-5 ─────────────────────────────
    print("1. Clipping seconds 2-5...")
    clip_out = str(work / "clipped.mp4")
    result = clip(test_video, clip_out, start="2", duration="3")
    print(f"   Output: {result.output_path}")
    print(f"   Command: {result.command}\n")

    # ── 2. Extract audio as 16kHz mono WAV (common for ASR) ──────
    print("2. Extracting audio as 16kHz mono WAV...")
    audio_out = str(work / "audio.wav")
    result = extract_audio(
        test_video, audio_out,
        codec="pcm_s16le", sample_rate=16000, channels=1,
    )
    print(f"   Output: {result.output_path}")
    size_kb = os.path.getsize(audio_out) / 1024
    print(f"   Size: {size_kb:.0f} KB\n")

    # ── 3. Transcode to 360p WebM ────────────────────────────────
    print("3. Transcoding to WebM (libvpx-vp9, CRF 35)...")
    webm_out = str(work / "transcoded.webm")
    result = transcode(
        test_video, webm_out,
        video_codec="libvpx-vp9", audio_codec="libopus",
        resolution="640x360", crf=35,
    )
    print(f"   Output: {result.output_path}\n")

    # ── 4. Merge: concatenate the clip with itself ────────────────
    print("4. Merging clipped.mp4 with itself...")
    merge_out = str(work / "merged.mp4")
    result = merge([clip_out, clip_out], merge_out)
    print(f"   Output: {result.output_path}\n")

    # ── 5. Probe: show media info ────────────────────────────────
    print("5. Probing the merged file...")
    info = exe.probe(merge_out)
    duration = info["format"].get("duration", "unknown")
    streams = len(info.get("streams", []))
    print(f"   Duration: {duration}s")
    print(f"   Streams: {streams}\n")

    print(f"All done! Output files are in: {work}")
    print("You can delete the temp directory when you're done exploring.")


if __name__ == "__main__":
    main()
